### ISSUE TITLE
Output can be incorrect depending on the last user to save the entry

### ISSUE THREAD

**Issue by elvdm** [craftcms/store-hours#20] opened 2017-11-08 23:26 UTC
Seems like the Store Hours output is often inaccurate on the front-end, depending on who last saved the entry with the Store Hours field.

We have found that when a user with their Week Start Day setting set to Sunday saves the entry, the output on the front-end is correct. When another user with their Week Start Day set to any other day saves the entry, the times do not match their corresponding days.

Our template is pretty similar as to what is recommended in the readme.

This issue was first noted after this [commit](https://github.com/craftcms/store-hours/commit/523961ad78343c8dd4cb07cc491df397e0f85dac) in this [issue](https://github.com/craftcms/store-hours/issues/11).

**Comment by brandonkelly** [comment] 2017-11-09 17:44
Duplicate of #19

(Just fixed in Store Hours 1.2.2 and 2.0.5.)

**Closed by brandonkelly** 2017-11-09 17:44 UTC
